name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:    
    name: github-actions-CI-CD    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag flask:$(date +%s)        